import { App } from './firebase-context.js';

Object.assign(App, {
    renderModals() {
        const container = document.getElementById('modals-container');
        if (!container) return;
        container.innerHTML = `
        <div id="modal-confirm" class="modal hide fixed inset-0 bg-slate-950/65 backdrop-blur-sm z-[120] flex items-center justify-center p-4"><div class="bg-white rounded-2xl shadow-2xl w-full max-w-sm p-6 text-center"><div class="w-14 h-14 bg-red-100 text-red-600 rounded-full flex items-center justify-center mx-auto mb-4"><i class="fa-solid fa-triangle-exclamation text-2xl"></i></div><h2 id="modal-confirm-title" class="text-xl font-black text-slate-800">Confirmação</h2><p id="modal-confirm-message" class="text-sm text-slate-500 mt-2 mb-6">Deseja continuar?</p><div class="grid grid-cols-2 gap-3"><button id="btn-confirm-cancel" type="button" class="py-3 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-extrabold">Cancelar</button><button id="btn-confirm-action" type="button" class="py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl font-extrabold">Confirmar</button></div></div></div>

        <div id="modal-action-options" class="modal hide fixed inset-0 bg-slate-950/60 backdrop-blur-sm z-[105] flex items-end sm:items-center justify-center sm:p-4"><div id="scope-options-content" class="bg-white rounded-t-3xl sm:rounded-2xl shadow-2xl w-full max-w-sm p-6"></div></div>

        <div id="modal-card" class="modal hide fixed inset-0 bg-slate-950/50 backdrop-blur-sm z-[90] flex items-center justify-center p-3"><div class="bg-white rounded-2xl shadow-2xl w-full max-w-sm overflow-hidden"><header class="px-5 py-4 bg-slate-50 border-b flex justify-between items-center"><h2 class="font-black text-slate-800">Cartão de crédito</h2><button type="button" onclick="App.closeModal('modal-card')" class="action-icon"><i class="fa-solid fa-xmark"></i></button></header><form onsubmit="App.saveCard(event)" class="p-5 space-y-4"><input type="hidden" id="card-id"><div><label class="block text-sm font-bold text-slate-700 mb-1">Nome do banco/cartão</label><input id="card-name" required class="input-modern" placeholder="Ex.: Nubank"></div><div><label class="block text-sm font-bold text-slate-700 mb-1">Dia do vencimento da fatura</label><input id="card-due" type="number" min="1" max="31" required class="input-modern" placeholder="Ex.: 10"></div><button type="submit" class="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-extrabold shadow">Salvar cartão</button></form></div></div>

        <div id="modal-transaction" class="modal hide fixed inset-0 bg-slate-950/50 backdrop-blur-sm z-[90] flex items-center justify-center p-2 sm:p-4"><div class="modal-panel bg-white rounded-2xl shadow-2xl w-full max-w-md"><header class="sticky top-0 z-10 px-5 py-4 bg-slate-50 border-b flex justify-between items-center"><h2 id="modal-trans-title" class="font-black text-slate-800">Registrar gasto</h2><button type="button" onclick="App.closeModal('modal-transaction')" class="action-icon"><i class="fa-solid fa-xmark"></i></button></header><form onsubmit="App.saveTransaction(event)" class="p-5 space-y-4"><input type="hidden" id="trans-id"><div><label class="block text-sm font-bold text-slate-700 mb-1">Descrição</label><input id="trans-desc" required class="input-modern" autocomplete="off" placeholder="Ex.: Compra no mercado"></div>${this.renderCategoryField('trans')}<div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label id="label-trans-amount" class="block text-sm font-bold text-slate-700 mb-1">Valor total</label><input id="trans-amount" required class="input-modern font-black text-blue-700" oninput="App.applyCurrencyMask(this)" placeholder="R$ 0,00"></div><div><label class="block text-sm font-bold text-slate-700 mb-1">Fatura inicial</label><div class="relative"><input type="month" id="trans-month" required class="native-picker" onchange="document.getElementById('trans-month-display').value=App.formatMonthSmall(this.value)"><input id="trans-month-display" class="input-modern font-bold" readonly placeholder="Mês"></div></div></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-4"><label class="block text-sm font-bold text-slate-700 mb-1">Forma do lançamento</label><select id="trans-type" onchange="App.toggleTransactionInstallments()" class="input-modern bg-white"><option value="vista">À vista (1x)</option><option value="parcelado">Parcelado</option><option value="recorrente">Recorrente mensal</option></select><div id="div-trans-installments" class="hide mt-3"><label class="block text-sm font-bold text-slate-700 mb-1">Quantidade de parcelas</label><input id="trans-installments" type="number" min="2" max="120" value="2" class="input-modern text-center font-black"></div></div><button type="submit" class="w-full py-3.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-extrabold shadow">Salvar lançamento</button></form></div></div>

        <div id="modal-account" class="modal hide fixed inset-0 bg-slate-950/50 backdrop-blur-sm z-[90] flex items-center justify-center p-2 sm:p-4"><div class="modal-panel bg-white rounded-2xl shadow-2xl w-full max-w-md"><header class="sticky top-0 z-10 px-5 py-4 bg-slate-50 border-b flex justify-between items-center"><h2 id="modal-account-title" class="font-black text-slate-800">Nova conta</h2><button type="button" onclick="App.closeModal('modal-account')" class="action-icon"><i class="fa-solid fa-xmark"></i></button></header><form onsubmit="App.saveAccount(event)" class="p-5 space-y-4"><input type="hidden" id="account-id"><div><label class="block text-sm font-bold text-slate-700 mb-1">Tipo</label><select id="account-kind" class="input-modern font-bold"><option value="payable">Conta a Pagar</option><option value="receivable">Conta a Receber</option></select></div><div><label class="block text-sm font-bold text-slate-700 mb-1">Descrição</label><input id="account-desc" required class="input-modern" autocomplete="off" placeholder="Ex.: Aluguel, venda para cliente"></div>${this.renderCategoryField('account')}<div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label id="label-account-amount" class="block text-sm font-bold text-slate-700 mb-1">Valor total</label><input id="account-amount" required class="input-modern font-black text-emerald-700" oninput="App.applyCurrencyMask(this)" placeholder="R$ 0,00"></div><div><label class="block text-sm font-bold text-slate-700 mb-1">Primeiro vencimento</label><input id="account-due-date" type="date" required class="input-modern font-bold"></div></div><div class="bg-slate-50 border border-slate-200 rounded-xl p-4"><label class="block text-sm font-bold text-slate-700 mb-1">Forma da conta</label><select id="account-type" onchange="App.toggleAccountInstallments()" class="input-modern bg-white"><option value="vista">À vista (1x)</option><option value="parcelado">Parcelada</option><option value="recorrente">Recorrente mensal</option></select><div id="div-account-installments" class="hide mt-3"><label class="block text-sm font-bold text-slate-700 mb-1">Quantidade de parcelas</label><input id="account-installments" type="number" min="2" max="120" value="2" class="input-modern text-center font-black"></div></div><p id="account-edit-note" class="hide text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg p-3">Em alterações de várias parcelas, os vencimentos originais são mantidos.</p><button type="submit" class="w-full py-3.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-extrabold shadow">Salvar conta</button></form></div></div>`;
    },

});
